### ISSUE TITLE
Bug: Customizable Elytra (customizableelytra) encountered an error during the common_setup event phase (Registry Object not present: aether:golden_parachute)

### ISSUE THREAD

**Issue by MoonMoonShark** [Hidoni/CustomizableElytra#35] opened 2023-12-18 21:22 UTC
seems to be a conflict with Customizable Elytra and The Aether: Redux. i've been trying to run them together in my modpack, but whenever i have them both, the game crashes on startup. i tried making a modpack with the bare minimum mods, and it crashes. when i remove redux, it loads.

**Specs:**
Minecraft 1.19.2
Forge 43.2.23

**Sample Modpack (doesn't work when Redux enabled):**
- Customizable Elytra (customizableelytra-1.19.0-1.7.4)
- Aeroblender (aeroblender-r1.19.2-1.0)
- The Aether (aether-1.19.2-1.0.0-beta.2.2-forge)
- The Aether: Redux (aether-redux-1.3.3-1.19.2-forge)
- TerraBlender (TerraBlender-forge-1.19.2-2.0.1.166)

**Crash Log:** https://pastebin.com/PcgBvsJW

please let me know if there is anything at all i can do to help! thank you for everything!

**Comment by Hidoni** [comment] 2023-12-18 21:45
Heya, thanks for reporting this!  
This bug is caused by The Aether: Redux, not this mod. It changes a function in the game and Customizable Elytra calls it earlier than they expect which causes their mod to access an item before it exists and crash.

This has to be fixed on their end, so I'd suggest you open an issue on their issue tracker! ^^

**Comment by MoonMoonShark** [comment] 2023-12-18 23:06
thank you for the quick response! i'll follow up with them.

**Closed as completed** 2024-03-02 08:53 UTC
Labels: bug
